version: '3.8'

services:
  frontend:
    image: node:14-alpine
    container_name: frontend
    restart: always
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_CLERK_PUBLISHABLE_KEY=your_clerk_publishable_key
    command: ["npm", "start"]

  clerk:
    image: clerk/clerk-spa
    container_name: clerk
    restart: always
    environment:
      - CLERK_PUBLISHABLE_KEY=your_clerk_publishable_key
    ports:
      - "3030:3030"

